######################################## 
# nginx reverse proxy by jwilder
######################################## 
nginx-proxy:
  ports:
    - "80:80"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
  image: jwilder/nginx-proxy
  restart: always
######################################## 
# Container based on tutum/wordpress - all in one demo - not good for production 
######################################## 
c1:
  image: tutum/wordpress
  expose:
    - "80"
  environment:
    - VIRTUAL_HOST=c1
  restart: always
######################################## 
# Container based on Library Wordpress 
######################################## 
wp:
  image: wordpress
  expose:
    - "80"
  environment:
    - WORDPRESS_DB_PASSWORD=password
    - VIRTUAL_HOST=some-host
  links:
    - db:mysql
  volumes:
    - ~/wp-content:/var/www/html/wp-content
  restart: always
######################################## 
# Container based on Library MySQL 
######################################## 
db:
  image: mysql:5.6
  volumes_from:
    - data
  volumes:
    - ~/etc/mysql/conf.d:/etc/mysql/conf.d
  environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_USER=user
    - MYSQL_PASSWORD=password
    - MYSQL_DATABASE=db
  restart: always
######################################## 
# Empty container to store data from db
######################################## 
data:
  build: data
######################################## 
# Joomla --- needs db 
######################################## 
google:
  image: joomla
  links:
    - db:mysql
  expose:
    - "80"
  environment:
    - VIRTUAL_HOST=google.com
######################################## 
# Redmine --- needs pg 
######################################## 
cnn:
  image: redmine
  expose:
    - "3000"
  links:
    - pg:postgres
  environment:
    - VIRTUAL_HOST=cnn.com
######################################## 
# Container based on Library postgres
######################################## 
pg:
  environment:
    - POSTGRES_PASSWORD=secret
    - POSTGRES_USER=redmine
  image: postgres
######################################## 
