################################################################################
# Copy YAML snippets from the example files, paste into this file
# and compose your stack by running
# docker compose up -d
################################################################################
