data:
  build: data

db:
  image: mysql:5.6
  volumes_from:
    - data
  volumes:
    - /home/user/dockerfiles/etc/mysql/conf.d:/etc/mysql/conf.d
  environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_USER=user
    - MYSQL_PASSWORD=password
    - MYSQL_DATABASE=db
  restart: always

wp:
  image: wordpress
  expose:
    - "80"
  environment:
    - WORDPRESS_DB_PASSWORD=password
    - VIRTUAL_HOST=some-host
  links:
    - db:mysql
  volumes:
    - /home/user/dockerfiles/wp-content:/var/www/html/wp-content
  restart: always


c1:
  image: tutum/wordpress
  expose:
    - "80"
  environment:
    - VIRTUAL_HOST=c1
  restart: always

nginx-proxy:
  ports:
    - "80:80"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
  image: jwilder/nginx-proxy
  restart: always

google:
  image: joomla
  links:
    - db:mysql
  expose:
    - "80"
  environment:
    - VIRTUAL_HOST=google.com

pg:
  environment:
    - POSTGRES_PASSWORD=secret
    - POSTGRES_USER=redmine
  image: postgres


cnn:
  image: redmine
  expose:
    - "3000"
  links:
    - pg:postgres
  environment:
    - VIRTUAL_HOST=cnn.com
